spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitlab.com/wsx180808/spring-cloud-config.git
          search-paths: respo
          username: 935770480@qq.com
          password: wsx180808

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/